#Control
TOP_LEFT = (0,0)
OPEN_DURATION = 360
BLINK_DURATION = 2
EXPRESSION_DURATION = 600
HEIGHT = 600
WIDTH = 1024
FPS = 30
GAME_NAME = 'Falling Carrots'

#bunny
BUNNY_SIZE = 32
STARTING_POS_X_BUNNY = 516
STARTING_POS_Y_BUNNY = 400
BUNNY_IMG = 'assets/bunny_64.png'
BUNNY_SPEED = 5
LEFT = -1
RIGHT = 1

#carrot
CARROT_IMG = 'assets/carrot_64.png'
STARTING_POS_Y_CARROT = 0
MIN_CARROT_SPEED = 1
MAX_CARROT_SPEED = 5
CARROT_SIZE = 64
CARROT_COLOR = (183, 65, 14)
NUMBER_CARROT = 5

#meteor
METEOR_IMG = 'assets/meteor_64.png'
STARTING_POS_Y_METEOR = 0
MIN_METEOR_SPEED = 1
MAX_METEOR_SPEED = 5
METEOR_SIZE = 64
NUMBER_METEOR = 3

#heart
HEART_IMG = 'assets/heart_32.png'
STARTING_POS_X_HEART = 20
STARTING_POS_Y_HEART = 20
HEART_SIZE = 32
NUM_HEARTS = 3

#score_board
SCORE_BOARD_IMG = 'assets/carrot_32.png'

#ground
GROUND_POS_Y = 400

#background
BACKGROUND_IMG = 'assets/background.png'
MENUE_BACKGROUND = (135, 206, 235)
DISPLAY_DURATION = 1000
#sound
SOUND_DIR = '/sound'
